Remove quay.io dependency for squid docker image. PYTHON-1228
Try to pull the squid docker image from quay.io, in order to avoid
the lengthy build process. But, if 'docker pull' fails, ignore the
error and build it the slow way.

Previously, there was no fallback, so if the 'docker pull' command
failed, the script would throw an error, rather than building the
squid image from the Dockerfile.

diff --git a/docker/packnsend b/docker/packnsend
--- a/docker/packnsend
+++ b/docker/packnsend
@@ -325,11 +325,21 @@ create_docker_base_images()
 
     echo "Image: squid"
 
-    # Commenting out build command. Will pull image from quay.io, instead.
+    # Try pulling the squid image from quay.io before building it.
 
-    # (cd $ROOT_DIRECTORY; docker build --rm -t squid docker/squid)
+    # If the pull succeeds, tag it and build it, so we end up with an image
+    # named 'squid'. Even though the build step is redundant after a successful
+    # pull, it doesn't hurt to run 'docker build', since the presence of the
+    # cached layers will make the build step very fast.
 
-    docker pull quay.io/newrelic/python-agent-squid
+    # If the pull and/or tag fails, ignore the errors and build it the slow
+    # way, without the benefit of cached layers.
+
+    docker pull quay.io/newrelic/python-agent-squid || true
+
+    docker tag quay.io/newrelic/python-agent-squid squid || true
+
+    (cd $ROOT_DIRECTORY; docker build --rm -t squid docker/squid)
 }
 
 start_application_services()
@@ -358,7 +368,7 @@ start_application_services()
 
     echo "Application: squid"
 
-    docker run -d --name packnsend-squid quay.io/newrelic/python-agent-squid
+    docker run -d --name packnsend-squid squid
 }
 
 stop_application_services()
