Use dogestry for packnsend push/pull. PYTHON-1983
Also, add idempotent start function

Replace existing code for push and pull to instead use dogestry. It assumes
that the user has the dogestry binary and the necessary AWS keys in place.

Add pull_with_restart function that will pull images from dogestry then restart
any containers whose images had changed as a result. It does not stop any
containers whose images did not change. Lastly, it ensures that all containers
are running. Note that this is different than running `packnsend pull` then
`packnsend start` which does not restart any containers whose images had
changed.

Add start_safe function that will not fail if a container is already running or
had previously stopped. Note that this is different from running `packnsend
start` which could return a non-zero exit code in those cases.

diff --git a/docker/packnsend b/docker/packnsend
--- a/docker/packnsend
+++ b/docker/packnsend
@@ -3,6 +3,9 @@
 ROOT_DIRECTORY=$(git rev-parse --show-toplevel)
 WORK_DIRECTORY=".`pwd | sed -e s%$ROOT_DIRECTORY%%`"
 
+DOGESTRY_BUCKET=s3://nr-docker-images-dev/?region=us-west-2
+DOGESTRY_IMG_PATH=datanerd.us/python_agent
+
 TEST_IMAGE_NAME=python-base
 
 TMPDIR=${TMPDIR:-/tmp}
@@ -366,54 +369,6 @@ create_docker_base_images_nocache()
     done
 }
 
-query_push_pull_authorization()
-{
-    # Determine if we are authorized to push and pull to the docker
-    # repository by attempting to pull a non-existent image and checking
-    # the HTTP status code in the response.
-    #
-    #       If we are authorized, status code is 404.
-    #       If we are not authorized, status code is 403.
-    #
-    # Set IS_AUTHORIZED_TO_PUSH_PULL to 'true' or 'false', depending on
-    # the response
-
-    DOCKER_REPO=quay.io
-    NONEXISTENT_IMAGE=$DOCKER_REPO/newrelic/python-agent-nonexistent
-
-    # Stderr will contain HTTP status code of response. Since we are pulling
-    # a non-existent image, we'll always get an error code of some sort.
-
-    PULL_RESPONSE=$(docker pull $NONEXISTENT_IMAGE 2>&1 >/dev/null)
-
-    PULL_RESPONSE_HTTP_STATUS=$(echo "$PULL_RESPONSE" | \
-        sed "s/.*HTTP code://" | tr -d [:space:])
-
-    if test $PULL_RESPONSE_HTTP_STATUS == '404'
-    then
-        IS_AUTHORIZED_TO_PUSH_PULL='true'
-
-    elif test $PULL_RESPONSE_HTTP_STATUS == '403'
-    then
-        IS_AUTHORIZED_TO_PUSH_PULL='false'
-
-        echo "You are not authorized to push or pull to the docker repository."
-        echo "To become authorized, create an account, then run 'docker login'"
-        echo "to create a .dockercfg file."
-        echo
-
-    else
-        # Any HTTP response code except 403 or 404 most likely means push/pull
-        # won't work, so set to false and display response code.
-
-        IS_AUTHORIZED_TO_PUSH_PULL='false'
-
-        echo "Error connecting to Docker repository:"
-        echo "$PULL_RESPONSE"
-        echo
-    fi
-}
-
 push_docker_base_images()
 {
     IMAGE_LIST=${@:-$ALL_IMAGES}
@@ -422,28 +377,17 @@ push_docker_base_images()
     echo "Push docker base images."
     echo "$IMAGE_LIST"
 
-    query_push_pull_authorization
+    for IMG in $IMAGE_LIST
+    do
 
-    if test $IS_AUTHORIZED_TO_PUSH_PULL = 'true'
-    then
-
-
-        for IMG in $IMAGE_LIST
-        do
-
-            echo
-            echo "Push image: $IMG"
-            echo
-
-            docker tag $IMG quay.io/newrelic/python-agent-$IMG
-            docker push quay.io/newrelic/python-agent-$IMG
-
-        done
-
-    else
-        echo "Skipping docker push."
         echo
-    fi
+        echo "Push image: $IMG"
+        echo
+
+        docker tag -f $IMG $DOGESTRY_IMG_PATH/$IMG
+        dogestry push $DOGESTRY_BUCKET $DOGESTRY_IMG_PATH/$IMG
+
+    done
 }
 
 pull_docker_base_images()
@@ -454,30 +398,54 @@ pull_docker_base_images()
     echo "Pull docker base images."
     echo "$IMAGE_LIST"
 
-    query_push_pull_authorization
+    for IMG in $IMAGE_LIST
+    do
 
-    if test $IS_AUTHORIZED_TO_PUSH_PULL = 'true'
-    then
-
-        IMAGE_LIST=${@:-$ALL_IMAGES}
-        IMAGE_LIST=$(echo $IMAGE_LIST | sed 's/ \+/ /g')
-
-        for IMG in $IMAGE_LIST
-        do
-
-            echo
-            echo "Pull image: $IMG"
-            echo
-
-            docker pull quay.io/newrelic/python-agent-$IMG
-            docker tag quay.io/newrelic/python-agent-$IMG $IMG
-
-        done
-
-    else
-        echo "Skipping docker pull."
         echo
-    fi
+        echo "Pull image: $IMG"
+        echo
+
+        dogestry -disable-checks pull $DOGESTRY_BUCKET $DOGESTRY_IMG_PATH/$IMG > /dev/null
+        docker tag -f $DOGESTRY_IMG_PATH/$IMG $IMG
+
+    done
+}
+
+pull_docker_images_and_restart() {
+    # Perform a dogestry pull. If the image changed from what was already on
+    # disk, stop the container if it is running. Finally, start the container
+    # ensuring that at the end of this function, all containers will be
+    # running.
+    IMAGE_LIST=${@:-$ALL_IMAGES}
+    IMAGE_LIST=$(echo $IMAGE_LIST | sed 's/ \+/ /g')
+
+    echo "Pull docker base images. Restarting those that have changed."
+    echo "$IMAGE_LIST"
+
+
+    for IMG in $IMAGE_LIST
+    do
+
+        echo
+        echo "Pull image: $IMG"
+        echo
+
+        before_sha=$(docker images -q ${IMG})
+        dogestry -disable-checks pull $DOGESTRY_BUCKET $DOGESTRY_IMG_PATH/$IMG > /dev/null
+        docker tag -f $DOGESTRY_IMG_PATH/$IMG $IMG
+        after_sha=$(docker images -q ${IMG})
+
+        if [ "$before_sha" != "$after_sha" ]
+        then
+            echo "New image sha found"
+            echo "Stopping existing container"
+            stop_application_services $IMG
+        else
+            echo "Image unchanged"
+        fi
+        echo "Starting container"
+        start_application_services_safe $IMG
+    done
 }
 
 start_application_services()
@@ -492,6 +460,38 @@ start_application_services()
 
         echo
         echo "Start: $IMG"
+
+        docker run -d --name packnsend-$IMG $IMG
+
+    done
+}
+
+start_application_services_safe()
+{
+    IMAGE_LIST=${@:-$APP_SERVICE_IMAGES}
+    IMAGE_LIST=$(echo $IMAGE_LIST | sed 's/ \+/ /g')
+
+    echo "Start application services."
+
+    for IMG in $IMAGE_LIST
+    do
+
+        echo
+        echo "Start: $IMG"
+
+        # is container already running?
+        docker ps | grep packnsend-$IMG > /dev/null
+        if [[ $? != 1 ]] ; then
+            echo "$IMG already running"
+            continue
+        fi
+        # is container stopped?
+        docker ps -a | grep packnsend-$IMG > /dev/null
+        if [[ $? != 1 ]] ; then
+            echo "$IMG has stopped, restarting"
+            docker start packnsend-$IMG
+            continue
+        fi
 
         docker run -d --name packnsend-$IMG $IMG
 
@@ -570,14 +570,17 @@ print_usage()
     echo "management commands. Otherwise, management commands operate"
     echo "on all images/containers."
     echo
-    echo "    init           Pull images, if authorized, else build."
-    echo "    build          Build base images."
-    echo "    build_nocache  Build base images, no cache."
-    echo "    push           Push base images."
-    echo "    pull           Pull base images."
-    echo "    start          Start base containers."
-    echo "    stop           Stop base containers."
-    echo "    cleanup        Delete base images."
+    echo "    init               Pull images, if authorized, else build."
+    echo "    build              Build base images."
+    echo "    build_nocache      Build base images, no cache."
+    echo "    push               Push base images."
+    echo "    pull               Pull base images."
+    echo "    pull_with-restart  Pull base images, restart if changed."
+    echo "    start              Start base containers."
+    echo "    start_safe         Start base containers, do not error "
+    echo "                       if already running."
+    echo "    stop               Stop base containers."
+    echo "    cleanup            Delete base images."
     echo
     echo "Help commands:"
     echo "    list           List base images."
@@ -632,6 +635,8 @@ case "$COMMAND" in
 
     init)
         pull_docker_base_images "$@"
+        # this variable is no longer set after running pull_docker_base_images,
+        # it is kept here for historical purposes
         if test $IS_AUTHORIZED_TO_PUSH_PULL = 'false'
         then
             create_docker_base_images "$@"
@@ -654,8 +659,16 @@ case "$COMMAND" in
         pull_docker_base_images "$@"
         ;;
 
+    pull_with_restart)
+        pull_docker_images_and_restart "$@"
+        ;;
+
     start)
         start_application_services "$@"
+        ;;
+
+    start_safe)
+        start_application_services_safe "$@"
         ;;
 
     stop)
